name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          elixir-version: 1.12
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run unit tests
        run: |
          mix test
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          elixir-version: 1.12
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run integration tests
        run: |
          mix test.integration
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          elixir-version: 1.12
      - name: Retrieve cached PLT
        uses: actions/cache@v1
        id: plt-cache
        with:
          path: .dialyzer
          key: plt-${{ github.head_ref }}
          restore-keys: |
            plt-${{ github.base_ref }}
            plt-main
            plt-
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run formatter
        run: |
          mix format --check-formatted

      - name: Create PLTs
        if: ${{ steps.plt-cache.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p .dialyzer
          mix dialyzer --plt

      - name: Run dialyzer
        run: |
          mix dialyzer
