name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  formatter:
    name: Formatter Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.2
          elixir-version: 1.9.4
      - name: Run formatter check
        run: |
          mix format --check-formatted
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.2
          elixir-version: 1.9.4
      - name: Get depedencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run unit tests
        run: |
          mix test
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.2
          elixir-version: 1.9.4
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run integration tests
        run: |
          mix test.integration
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.2
          elixir-version: 1.9.4
      - name: Retrieve cached PLT
        uses: actions/cache@v1
        with:
          path: .dialyzer
          key: dialyzer-plt
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run dialyzer
        run: |
          mix dialyzer
